[package]
name = "Tuple-Hash-Crasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.5"
fxhash = "0.2.1"

[profile.release]
debug = true